target("collab.core")
    set_kind("static")
    add_files("src/**.cpp")
    add_files("src/**.cppm", { public = true })
    add_packages("fmt", { public = true })
    add_packages("spdlog")
    add_packages("rang")

target("collab.core.hpp")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/include", { public = true })
    add_headerfiles("$(projectdir)/include/(collab/**.hpp)")
    add_packages("fmt", { public = true })

if get_config("build_tests") then
    target("tests-collab.core")
        set_kind("binary")
        add_files("tests/*.cpp")
        add_deps("collab.core")
        add_packages("catch2")
        set_rundir("$(projectdir)")
        add_tests("default", {runargs = {"--durations", "yes"}})

    target("tests-collab.core.hpp")
        set_kind("binary")
        add_files("tests/hpp/*.cpp")
        add_deps("collab.core.hpp")
        add_packages("catch2")
        set_rundir("$(projectdir)")
        add_tests("default", {runargs = {"--durations", "yes"}})
end
