// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/atomic_file_writer.hpp>

module collab;

namespace {
using namespace ::collab;
#if defined(__GNUC__) || defined(__clang__)
[[gnu::used]]
#endif
[[maybe_unused]] const void* const _emit_atomic_file_writer_symbols[] = {
    reinterpret_cast<const void*>(static_cast<void (*)(std::filesystem::path, std::span<const std::byte>)>(&::collab::atomic_file_write)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::filesystem::path, std::string_view)>(&::collab::atomic_file_write)),
};
}
