// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/detail/fixed_string.decls.hpp>

export module collab:fixed_string;

export namespace collab {
    using ::collab::basic_fixed_string;
    using ::collab::swap;
    using ::collab::fixed_string;
    using ::collab::fixed_u8string;
    using ::collab::fixed_u16string;
    using ::collab::fixed_u32string;
    using ::collab::fixed_wstring;
}
