// Generated by scripts/generate.py — do not edit by hand.

#pragma once

#include <filesystem>
#include <memory>
#include <mutex>
#include <string_view>
#include <utility>
#include <vector>

#include <fmt/format.h>

#include <collab/identifier.hpp>

namespace collab::log {

enum class level { trace, debug, info, warn, error, critical, off };

class sink {
public:
    virtual ~sink() = default;
    virtual void write(level lvl,
                       const collab::identifier* id,
                       std::string_view msg) = 0;
};

}  // namespace collab::log

namespace collab::log::detail {

// Namespace-scope inline variable: COMDAT-folded by the linker across every
// TU that sees this declaration, regardless of module attachment. A function-
// local static would fragment if module attachment split the enclosing
// function into two entities — namespace-scope inline survives that.
struct log_state {
    level                              current_level = level::info;
    std::vector<std::unique_ptr<sink>> sinks;
    std::mutex                         mtx;
};

extern log_state g_state;

}  // namespace collab::log::detail

namespace collab::log {

// ── State management ────────────────────────────────────────────────────

void set_level(level);

level get_level();

void add_sink(std::unique_ptr<sink>);

void clear_sinks();

void log_message(level, const collab::identifier*, std::string_view);

// ── Untagged free functions: anonymous logging, no library attribution ──

void trace(std::string_view);
void debug(std::string_view);
void info(std::string_view);
void warn(std::string_view);
void error(std::string_view);
void critical(std::string_view);

// ── Tagged free functions: message carries the caller's identifier ────────

void trace_with(const collab::identifier&, std::string_view);
void debug_with(const collab::identifier&, std::string_view);
void info_with(const collab::identifier&, std::string_view);
void warn_with(const collab::identifier&, std::string_view);
void error_with(const collab::identifier&, std::string_view);
void critical_with(const collab::identifier&, std::string_view);

// ── fmt-style variadic overloads ──────────────────────────────────────────
// The level check here avoids paying fmt::format cost for filtered messages.
// A benign TOCTOU exists (level could change between the check and dispatch)
// — acceptable for logging.

template<typename... Args>
void trace(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::trace)
        trace(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void debug(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::debug)
        debug(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void info(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::info)
        info(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void warn(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::warn)
        warn(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void error(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::error)
        error(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void critical(fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::critical)
        critical(std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void trace_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::trace)
        trace_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void debug_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::debug)
        debug_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void info_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::info)
        info_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void warn_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::warn)
        warn_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void error_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::error)
        error_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

template<typename... Args>
void critical_with(const collab::identifier& id, fmt::format_string<Args...> fs, Args&&... args) {
    if (get_level() <= level::critical)
        critical_with(id, std::string_view(fmt::format(fs, std::forward<Args>(args)...)));
}

// ── Library-bound logger ────────────────────────────────────────────────
// Each library declares a single static `identifier` and aliases the logger:
//
//   using log = collab::log::logger<my_lib::identifier>;
//
// then calls `log::info("...")` throughout. All methods are static — no
// per-call object construction. The identifier is baked into the template
// instantiation as a reference NTTP.

template<const collab::identifier& I>
struct logger {
    template<typename... Args>
    static void trace(fmt::format_string<Args...> fs, Args&&... args) {
        trace_with(I, fs, std::forward<Args>(args)...);
    }
    template<typename... Args>
    static void debug(fmt::format_string<Args...> fs, Args&&... args) {
        debug_with(I, fs, std::forward<Args>(args)...);
    }
    template<typename... Args>
    static void info(fmt::format_string<Args...> fs, Args&&... args) {
        info_with(I, fs, std::forward<Args>(args)...);
    }
    template<typename... Args>
    static void warn(fmt::format_string<Args...> fs, Args&&... args) {
        warn_with(I, fs, std::forward<Args>(args)...);
    }
    template<typename... Args>
    static void error(fmt::format_string<Args...> fs, Args&&... args) {
        error_with(I, fs, std::forward<Args>(args)...);
    }
    template<typename... Args>
    static void critical(fmt::format_string<Args...> fs, Args&&... args) {
        critical_with(I, fs, std::forward<Args>(args)...);
    }

    static void trace   (std::string_view msg) { trace_with   (I, msg); }
    static void debug   (std::string_view msg) { debug_with   (I, msg); }
    static void info    (std::string_view msg) { info_with    (I, msg); }
    static void warn    (std::string_view msg) { warn_with    (I, msg); }
    static void error   (std::string_view msg) { error_with   (I, msg); }
    static void critical(std::string_view msg) { critical_with(I, msg); }
};

// ── spdlog-backed sink factories ──────────────────────────────────────────
// Declarations only — definitions live in the impl unit so spdlog is a
// private link dependency. Header-only consumers that don't call these
// don't pick up a spdlog link requirement.

std::unique_ptr<sink> make_stdout_sink();
std::unique_ptr<sink> make_stdout_color_sink();
std::unique_ptr<sink> make_stderr_sink();
std::unique_ptr<sink> make_stderr_color_sink();
std::unique_ptr<sink> make_file_sink(std::filesystem::path path);

}  // namespace collab::log

