// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/log.hpp>

module collab;

namespace {
using namespace ::collab::log;
#if defined(__GNUC__) || defined(__clang__)
[[gnu::used]]
#endif
[[maybe_unused]] const void* const _emit_collab_log_symbols[] = {
    reinterpret_cast<const void*>(static_cast<void (*)(level)>(&::collab::log::set_level)),
    reinterpret_cast<const void*>(static_cast<level (*)()>(&::collab::log::get_level)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::unique_ptr<sink>)>(&::collab::log::add_sink)),
    reinterpret_cast<const void*>(static_cast<void (*)()>(&::collab::log::clear_sinks)),
    reinterpret_cast<const void*>(static_cast<void (*)(level, const collab::identifier*, std::string_view)>(&::collab::log::log_message)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::trace)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::debug)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::info)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::warn)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::error)),
    reinterpret_cast<const void*>(static_cast<void (*)(std::string_view)>(&::collab::log::critical)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::trace_with)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::debug_with)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::info_with)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::warn_with)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::error_with)),
    reinterpret_cast<const void*>(static_cast<void (*)(const collab::identifier&, std::string_view)>(&::collab::log::critical_with)),
};
}
