// Generated by scripts/generate.py — do not edit by hand.

module;

#include "publisher.decls.hpp"

export module collab:publisher;

export namespace collab {
    using ::collab::subscription;
    using ::collab::publisher;
}
