// Generated by scripts/generate.py — do not edit by hand.

#pragma once

#include <algorithm>
#include <cstddef>
#include <functional>
#include <memory>
#include <mutex>
#include <shared_mutex>
#include <utility>
#include <vector>

// ─────────────────────────────────────────────────────────────────────────────
// 📡 collab::publisher — multi-subscriber, thread-safe pub/sub primitive.
//
// Publishing is `operator()`, not `emit()`. Qt's qtmetamacros.h defines `emit`
// as an empty preprocessor macro, which silently mangles any `pub.emit(args)`
// call in a TU that also includes a Qt header. Using call syntax sidesteps
// that collision entirely — `pub(args)` reads naturally and survives Qt.
//
// Threading contract
// ──────────────────
//   • connect(), operator(), disconnect(), and subscriber_count() are all
//     safe to call concurrently from any thread on the same publisher.
//   • operator() does not hold the internal lock while invoking handlers. It
//     snapshots the subscriber list under a shared lock, releases the lock,
//     then iterates. Reentrancy and recursive publication are deadlock-free.
//   • A handler invoked from operator() may freely call connect(),
//     disconnect(), or operator() (including on the same publisher).
//   • Disconnect during an in-flight publication affects subsequent
//     publications, not the current one. Handlers already captured in the
//     current snapshot still fire — their slots are kept alive by the
//     snapshot's shared_ptrs.
//   • A subscription may safely outlive its publisher. Disconnect becomes a
//     no-op once the publisher is destroyed. No use-after-free is possible.
//
// Convention
// ──────────
//   Only the class that owns the publisher invokes it. The type system does
//   not enforce this — code review and discipline do. Same convention as
//   Qt 5+, Boost.Signals2, sigc++.
// ─────────────────────────────────────────────────────────────────────────────

namespace collab {

namespace detail {

    struct subscriber_base {
        virtual ~subscriber_base() = default;
    };

    template <typename... Args>
    struct subscriber final : subscriber_base {
        std::function<void(Args...)> handler;
        explicit subscriber(std::function<void(Args...)> h) : handler(std::move(h)) {}
    };

    struct publisher_control_block {
        std::shared_mutex                             mutex;
        std::vector<std::shared_ptr<subscriber_base>> subscribers;
    };

}  // namespace detail

// 🎟 RAII subscription token. Move-only. Auto-disconnects on destruction.
// Safe to outlive its publisher — disconnect becomes a no-op then.
class subscription {
public:
    subscription() noexcept = default;

    subscription(std::function<void()> disconnect_fn,
                 std::function<bool()> connected_fn) noexcept
        : disconnect_fn_{std::move(disconnect_fn)},
          connected_fn_{std::move(connected_fn)} {}

    subscription(subscription&& other) noexcept
        : disconnect_fn_{std::move(other.disconnect_fn_)},
          connected_fn_{std::move(other.connected_fn_)} {
        other.disconnect_fn_ = nullptr;
        other.connected_fn_  = nullptr;
    }

    subscription& operator=(subscription&& other) noexcept {
        if (this != &other) {
            disconnect();
            disconnect_fn_       = std::move(other.disconnect_fn_);
            connected_fn_        = std::move(other.connected_fn_);
            other.disconnect_fn_ = nullptr;
            other.connected_fn_  = nullptr;
        }
        return *this;
    }

    subscription(const subscription&)            = delete;
    subscription& operator=(const subscription&) = delete;

    ~subscription() { disconnect(); }

    void disconnect() noexcept {
        if (disconnect_fn_) {
            disconnect_fn_();
            disconnect_fn_ = nullptr;
            connected_fn_  = nullptr;
        }
    }

    bool connected() const noexcept {
        return static_cast<bool>(connected_fn_) && connected_fn_();
    }

private:
    std::function<void()> disconnect_fn_;
    std::function<bool()> connected_fn_;
};

// 📡 Multi-subscriber publisher. See top-of-file contract for semantics.
template <typename... Args>
class publisher {
public:
    using handler = std::function<void(Args...)>;

    publisher() : control_{std::make_shared<detail::publisher_control_block>()} {}

    publisher(const publisher&)            = delete;
    publisher& operator=(const publisher&) = delete;
    publisher(publisher&&)                 = delete;
    publisher& operator=(publisher&&)      = delete;

    [[nodiscard]] subscription connect(handler fn) {
        auto sub_ptr =
            std::make_shared<detail::subscriber<Args...>>(std::move(fn));
        {
            std::unique_lock lock{control_->mutex};
            control_->subscribers.push_back(sub_ptr);
        }

        std::weak_ptr<detail::publisher_control_block> weak_ctrl = control_;
        std::weak_ptr<detail::subscriber_base>         weak_sub  = sub_ptr;

        return subscription{
            [weak_ctrl, weak_sub]() {
                auto ctrl = weak_ctrl.lock();
                if (!ctrl) return;
                auto sp = weak_sub.lock();
                if (!sp) return;
                std::unique_lock lock{ctrl->mutex};
                auto&            v  = ctrl->subscribers;
                auto             it = std::find(v.begin(), v.end(), sp);
                if (it != v.end()) v.erase(it);
            },
            [weak_ctrl, weak_sub]() -> bool {
                auto ctrl = weak_ctrl.lock();
                if (!ctrl) return false;
                auto sp = weak_sub.lock();
                if (!sp) return false;
                std::shared_lock lock{ctrl->mutex};
                const auto&      v = ctrl->subscribers;
                return std::find(v.begin(), v.end(), sp) != v.end();
            }};
    }

    void operator()(Args... args) {
        // Local strong ref keeps the control block alive if `*this` is
        // destroyed on another thread mid-publication. Without it, the lock
        // and snapshot lines below would access a freed control block.
        auto ctrl = control_;
        std::vector<std::shared_ptr<detail::subscriber_base>> snapshot;
        {
            std::shared_lock lock{ctrl->mutex};
            snapshot = ctrl->subscribers;
        }
        for (auto& base : snapshot) {
            // Every entry in our control_ is subscriber<Args...> by construction.
            auto* typed = static_cast<detail::subscriber<Args...>*>(base.get());
            typed->handler(args...);
        }
    }

    std::size_t subscriber_count() const {
        std::shared_lock lock{control_->mutex};
        return control_->subscribers.size();
    }

private:
    std::shared_ptr<detail::publisher_control_block> control_;
};

}  // namespace collab

