// Generated by scripts/generate.py — do not edit by hand.

#pragma once

#include <algorithm>
#include <compare>
#include <cstddef>
#include <string>
#include <string_view>
#include <vector>

namespace collab::detail {

std::vector<std::string_view> split_identifiers(std::string_view);

bool is_numeric_identifier(std::string_view);

unsigned long long parse_numeric(std::string_view);

// Pre-release precedence per SemVer §11. Caller guarantees both are non-empty.
std::strong_ordering compare_pre_release(std::string_view, std::string_view);

}  // namespace collab::detail

namespace collab {

struct semver {
    int         major = 0;
    int         minor = 0;
    int         patch = 0;
    std::string pre_release;
    std::string build;

    std::string to_string() const {
        std::string out;
        out.reserve(16);
        out += std::to_string(major);
        out += '.';
        out += std::to_string(minor);
        out += '.';
        out += std::to_string(patch);
        if (!pre_release.empty()) {
            out += '-';
            out += pre_release;
        }
        if (!build.empty()) {
            out += '+';
            out += build;
        }
        return out;
    }

    // Hand-written (not defaulted): SemVer §10 requires `build` to be ignored
    // when determining precedence; defaulting would include it.
    std::strong_ordering operator<=>(const semver& other) const {
        if (const auto cmp = major <=> other.major; cmp != 0) return cmp;
        if (const auto cmp = minor <=> other.minor; cmp != 0) return cmp;
        if (const auto cmp = patch <=> other.patch; cmp != 0) return cmp;

        const bool a_has = !pre_release.empty();
        const bool b_has = !other.pre_release.empty();
        if (!a_has && !b_has) return std::strong_ordering::equal;
        if (!a_has &&  b_has) return std::strong_ordering::greater;
        if ( a_has && !b_has) return std::strong_ordering::less;
        return detail::compare_pre_release(pre_release, other.pre_release);
    }

    bool operator==(const semver& other) const {
        return major == other.major
            && minor == other.minor
            && patch == other.patch
            && pre_release == other.pre_release;
    }
};

}  // namespace collab

