// Generated by scripts/generate.py — do not edit by hand.

module;

#include <collab/semver.hpp>

module collab;

namespace {
using namespace ::collab::detail;
#if defined(__GNUC__) || defined(__clang__)
[[gnu::used]]
#endif
[[maybe_unused]] const void* const _emit_collab_semver_symbols[] = {
    reinterpret_cast<const void*>(static_cast<std::vector<std::string_view> (*)(std::string_view)>(&::collab::detail::split_identifiers)),
    reinterpret_cast<const void*>(static_cast<bool (*)(std::string_view)>(&::collab::detail::is_numeric_identifier)),
    reinterpret_cast<const void*>(static_cast<unsigned long long (*)(std::string_view)>(&::collab::detail::parse_numeric)),
    reinterpret_cast<const void*>(static_cast<std::strong_ordering (*)(std::string_view, std::string_view)>(&::collab::detail::compare_pre_release)),
};
}
