// Generated by scripts/generate.py — do not edit by hand.

#pragma once

#include <iosfwd>

namespace collab::term {

// Terminal color/style manipulators.
// When streamed, these emit ANSI escape codes — unless output is piped,
// NO_COLOR is set, or the stream isn't a TTY. The impl uses rang internally
// to handle suppression and platform differences.

enum class color {
    black, red, green, yellow, blue, magenta, cyan, gray,
    reset
};

enum class style {
    bold, dim, italic, underline, blink, reversed, crossed,
    reset
};

std::ostream& operator<<(std::ostream& os, color c);
std::ostream& operator<<(std::ostream& os, style s);

// Convenience constants for `using namespace collab::term;`
namespace fg {
    inline constexpr color black   = color::black;
    inline constexpr color red     = color::red;
    inline constexpr color green   = color::green;
    inline constexpr color yellow  = color::yellow;
    inline constexpr color blue    = color::blue;
    inline constexpr color magenta = color::magenta;
    inline constexpr color cyan    = color::cyan;
    inline constexpr color gray    = color::gray;
}

inline constexpr color reset_color = color::reset;
inline constexpr style bold        = style::bold;
inline constexpr style dim         = style::dim;
inline constexpr style italic      = style::italic;
inline constexpr style underline   = style::underline;
inline constexpr style blink       = style::blink;
inline constexpr style reversed    = style::reversed;
inline constexpr style crossed     = style::crossed;
inline constexpr style reset_style = style::reset;

}  // namespace collab::term

